version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Esta línea es CLAVE: le dice a Postgres que no cree una base de datos
      # con el nombre del usuario. Esto fuerza a Odoo a mostrar el asistente.
      - POSTGRES_DB=postgres
    ports:
      - "5430:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo_network

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    # MUY IMPORTANTE: NO HAY SECCIÓN "command".
    # Dejamos que el punto de entrada por defecto de la imagen de Odoo haga su trabajo.
    env_file:
      - .env
    networks:
      - odoo_network

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_app
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=n8n_admin_2024
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Madrid
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge

volumes:
  odoo-web-data:
  odoo-db-data:
  n8n_data: