services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo_network

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    # IMPORTANTE la línea "-i base" solo se ejecuta la primera vez para inincializar la base de datos con el módulo base
    # luego se debe eliminar 
    # command: odoo -d odoo_db -i base --db_user=odoo --db_password=odoo --db_host=db
    # IMPORTANTE Si no se quiere inicializar la base de datos con el módulo base, usar la siguiente línea en su lugar:
    command: odoo -d odoo_db --db_user=odoo --db_password=odoo --db_host=db
    networks:
      - odoo_network
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_app
    environment:
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: n8n_admin_2024
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://localhost:5678/
      GENERIC_TIMEZONE: Europe/Madrid
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge

volumes:
  odoo-web-data:
  odoo-db-data:
  n8n_data:
